// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdACvGNTjbOlU5hpJDvuciWv_LPAAzFi0',
    appId: '1:121402716558:web:fb6cd8403df951bf38f4df',
    messagingSenderId: '121402716558',
    projectId: 'chat-app-73461',
    authDomain: 'chat-app-73461.firebaseapp.com',
    storageBucket: 'chat-app-73461.firebasestorage.app',
    measurementId: 'G-WQVMN4TQ33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrbly4X7x9EcUMgQW-VEVNhOegeAECKE',
    appId: '1:121402716558:android:aa795392f697cb2e38f4df',
    messagingSenderId: '121402716558',
    projectId: 'chat-app-73461',
    storageBucket: 'chat-app-73461.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCbEvrwnCekR9e7N0wkHAH-Xzg9J2CXw',
    appId: '1:121402716558:ios:8949b1cc39c619f038f4df',
    messagingSenderId: '121402716558',
    projectId: 'chat-app-73461',
    storageBucket: 'chat-app-73461.firebasestorage.app',
    iosBundleId: 'com.example.companyChatApp',
  );
}
